jobs:
  run-dbt:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install DBT
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install dbt

    - name: Set DBT API Key
      run: echo "DBT_CLOUD_API_KEY=${{ secrets.DBT_CLOUD_API_KEY }}" >> $GITHUB_ENV

    - name: Run DBT models
      run: |
        source venv/bin/activate
        dbt run --profiles-dir .
