version: 2

sources:
  - name: sales_database
    schema: sales_database
    tables:
      - name: order
      - name: order_item
      - name: product
  - name: google_sheets
    schema: google_sheets
    tables:
      - name: account_manager_region_mapping
